dist: trusty
sudo: false

language: python
python:
  - 2.7
  - 3.5
  - 3.6
  jobs:
    include:
      # Unit tests are run
      - stage: 'install'
        install:
          - python setup.py sdist
          - pip install dist/*.tar.gz
          - pip install mock --upgrade
          - pip install coveralls

        script:
          - coverage run --omit=pythesint/tests/* --source=pythesint setup.py test

        after_success:
          - coveralls

      - stage: 'pypi deployment'
      #if: tag IS present  
      deploy:
        - provider: pypi
          user: "__token__"
          password: "${PYPI_TOKEN}"
          on:
            all_branches: true
            #tags: true
